version: '3.3'
services:

  database:
    image: postgres:latest
    container_name: dash-rates-db
    environment:
      - PG_TRUST_LOCALNET=true
      - POSTGRES_USER=jeff
      - POSTGRES_PASSWORD=jeff
      - POSTGRES_DB=dash-rates-local

    ports:
      - "5432:5432"

  redis:
    image: redis:3.2.12
    container_name: dash-rates-cache
    ports:
      - "6379:6379"