version: '3.3'
services:

  database:
    image: sameersbn/postgresql:10
    container_name: dash-rates-db
    environment:
      - DB_NAME=dash-rates-local,dash-rates-test
      - PG_TRUST_LOCALNET=true
    ports:
      - "5432:5432"

  redis:
    image: redis:3.2.12
    container_name: dash-rates-cache
    ports:
      - "6379:6379"